version: "3.9"

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    env_file:
      - .env
    volumes:
      - neo4jdata:/data

volumes:
  neo4jdata:
  